# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170305_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateField(),
        ),
    ]
