# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170223_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('can_ notice', 'Can write notice'),)},
        ),
    ]
